name: Auto release to GPR

on:
  push:
    branches:
      - development
  pull_request:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    # THÊM ĐOẠN NÀY ĐỂ CẤP QUYỀN GHI PACKAGE CHO GITHUB_TOKEN
    permissions:
      contents: read
      packages: write 
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@curisiro'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Update Package Scope
        run: sed -i "s/@dimforge/@curisiro/g" rapier-compat/rollup.config.js

      - name: Prepare Rust projects
        run: bash ./builds/prepare_builds/prepare_all_projects.sh

      - name: Build Packages
        run: |
          cd rapier-compat
          npm install
          npm run build

      - name: Publish Packages (CD Release)
        if: github.event_name != 'pull_request'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          
          for PKG_DIR in rapier-compat/builds/*/pkg; do
            echo "Publishing $PKG_DIR..."
            cd "$PKG_DIR"
            
            # Sửa lại Repository URL thành repo của bạn để Github Packages cho phép publish
            npm pkg set repository.url="git+https://github.com/curisiro/rapier.js.git"
            
            # Đổi version
            npm version prerelease --preid="alpha.${SHORT_SHA}" --no-git-tag-version
            
            npm publish --access public
            cd -
          done
